### ISSUE TITLE
Dear ; after running the code , I got this error , X = np.vstack((X, np_img[o[0]:o[0]+img_dim[0], o[1]:o[1]+img_dim[1], :][np.newaxis])) TypeError: slice indices must be integers or None or have an __index__ method, would you please helpe me ?

### ISSUE THREAD

**Issue by NinaLLI** [lmzintgraf/DeepVis-PredDiff#3]

**Comment by lmzintgraf** [comment]
Can you tell me how I can reproduce that error? Which models and inputs did you use, and when/where does that error occur? You can re-open the issue then.

**Comment by maxkohlbrenner** [comment]
I had the same problem when running the program with all default settings of the latest commit (0d2463054ec3dc14b7ed29bf456f73031f1e3bf9) in cpu-only mode. Casting the values of o to int solved it for me.
Cheers,
Max

**Comment by albermax** [comment]
Hi Luisa,
with python 2.7 I still get this error:

```bash
Traceback (most recent call last):
  File "experiments_imagenet.py", line 79, in <module>
    X_test, X_test_im, X_filenames = utlD.get_imagenet_data(net=net)
  File "/home/bbdc/alber/tmp/zintgraf/DeepVis-PredDiff2/utils_data.py", line 46, in get_imagenet_data
    o = int(0.5*np.array([np_img.shape[0]-img_dim[0], np_img.shape[1]-img_dim[1]]))
TypeError: only length-1 arrays can be converted to Python scalars
```

Here is a suggestion for a fix:
```bash
diff --git a/utils_data.py b/utils_data.py
index c214175..0fd2319 100644
a/utils_data.py
b/utils_data.py
@@ -43,7 +43,7 @@ def get_imagenet_data(net):
    for i in range(len(img_list)):
        np_img = np.float32(PIL.Image.open('{}/{}'.format(path_data, img_list[i])))
        if np_img.shape[0] >= img_dim[0] and np_img.shape[1] >= img_dim[1]:
-            o = int(0.5*np.array([np_img.shape[0]-img_dim[0], np_img.shape[1]-img_dim[1]]))
+            o = (0.5*np.array([np_img.shape[0]-img_dim[0], np_img.shape[1]-img_dim[1]])).astype(np.uint)
            X = np.vstack((X, np_img[o[0]:o[0]+img_dim[0], o[1]:o[1]+img_dim[1], :][np.newaxis]))
            X_filenames.append(img_list[i].replace(".",""))
        else:
```

**Comment by gudovskiy** [comment]
@albermax looks like 'int' is more appropriate than 'uint' as:
o = (0.5*np.array([np_img.shape[0]-img_dim[0], np_img.shape[1]-img_dim[1]])).astype(np.int)
